version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverlerss-api-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ilhuuinustlq"
s3_prefix = "serverlerss-api-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
