name: Portfolio Tests
on: 
  push:
    branches:
      - main

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Test with unittest
        run: python tests/test_lambda_function.py -v
  
  build-and-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: SAM Validate
        run: |
          sam validate
      - run: sam build 
        working-directory: serverless-api-stack
      - run: sam deploy --no-confirm-changeset --nofail-on-empty-changeset
        working-directory: serverless-api-stack